"""Initial PostgreSQL schema

Revision ID: 0a2c5e85c896
Revises: 
Create Date: 2026-08-23 01:25:37.587363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2c5e85c896'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=True),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('interior_color', sa.String(length=50), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('badge', sa.String(length=30), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_body_type'), ['body_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_fuel'), ['fuel'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_transmission'), ['transmission'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_year'), ['year'], unique=False)

    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_is_active'), ['is_active'], unique=False)

    op.create_table('website_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('slogan', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('google_maps', sa.Text(), nullable=True),
    sa.Column('business_hours', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('tiktok', sa.String(length=255), nullable=True),
    sa.Column('hero_title', sa.String(length=255), nullable=True),
    sa.Column('hero_subtitle', sa.String(length=255), nullable=True),
    sa.Column('hero_image', sa.String(length=255), nullable=True),
    sa.Column('cars_sold', sa.Integer(), nullable=True),
    sa.Column('customers', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=80), nullable=True),
    sa.Column('social_image', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('smtp_host', sa.String(length=120), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=120), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('maintenance_message', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('car_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_image_car_id'), ['car_id'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_is_read'), ['is_read'], unique=False)

    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('test_drive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_drive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_drive_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_drive_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_drive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_drive_status'))
        batch_op.drop_index(batch_op.f('ix_test_drive_created_at'))

    op.drop_table('test_drive')
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_admin_id'))

    op.drop_table('password_reset_token')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_is_read'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))

    op.drop_table('message')
    with op.batch_alter_table('car_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_image_car_id'))

    op.drop_table('car_image')
    op.drop_table('website_settings')
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_is_active'))
        batch_op.drop_index(batch_op.f('ix_team_member_display_order'))

    op.drop_table('team_member')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_year'))
        batch_op.drop_index(batch_op.f('ix_car_transmission'))
        batch_op.drop_index(batch_op.f('ix_car_status'))
        batch_op.drop_index(batch_op.f('ix_car_price'))
        batch_op.drop_index(batch_op.f('ix_car_model'))
        batch_op.drop_index(batch_op.f('ix_car_is_featured'))
        batch_op.drop_index(batch_op.f('ix_car_fuel'))
        batch_op.drop_index(batch_op.f('ix_car_created_at'))
        batch_op.drop_index(batch_op.f('ix_car_brand'))
        batch_op.drop_index(batch_op.f('ix_car_body_type'))

    op.drop_table('car')
    op.drop_table('admin')
    # ### end Alembic commands ###
